version: '3.9'

services:
  school_management_db:
    image: mysql:8.0.31
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: school_management
    ports:
      - 3306:3306

  adminer:
    image: adminer:4.8.1
    ports:
      - 8080:8080
